version: 0.0
os: linux
files:
  - source: ./
    destination: /test
file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/html
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/restart_server.sh
      runas: root
  BeforeInstall:
    - location: scripts/restart_server.sh
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      runas: root
